[build]
  command = "npm run build"
  publish = "build"

[build.environment]
  NODE_ENV = "production"
  NPM_FLAGS = "--no-optional"
  CI = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200